//! Frozen state fixtures: can this build read what the previous one wrote?
//!
//! # Why this exists
//!
//! Upgrading a CDC server is the highest-stakes routine operation it has. The pipeline's
//! entire memory of where it is lives in the state directory, and if a new build cannot
//! read it the outcomes are both bad and both silent-ish: refuse to start (an outage), or
//! start from nothing (a full re-snapshot, or a slot rewind that replays weeks of change
//! data into a downstream nobody warned).
//!
//! Nothing checked that. Every state test in this repository writes with the current build
//! and reads with the current build, which is exactly the shape that cannot fail. The
//! upgrade path was covered by hoping.
//!
//! It is not hypothetical: 0.11 → 0.12 added two fields to `IncrementalSnapshotState`.
//! They carry `#[serde(default)]`, so old checkpoints load — but that was upstream's
//! decision, made in a crate this project does not own, and nothing here would have
//! noticed if it had gone the other way.
//!
//! # What is frozen, and what that buys
//!
//! Two kinds of fixture, and the distinction matters:
//!
//! * **Real artefacts**, byte-for-byte, in `tests/fixtures/state/`. The checkpoint file
//!   carries a `content_checksum`, so it cannot be hand-written or hand-edited — it was
//!   produced by a real `FileCheckpoint::save` and committed. If the format, the field
//!   names, the checksum algorithm or the checksum's input ever change, this fails.
//! * **Older shapes**, written inline as JSON. These are what a *previous* release
//!   produced, reconstructed from its schema. They cannot be generated by this build, and
//!   that is the point: they are the only way to test the direction upgrades actually
//!   travel.
//!
//! # What this does not test
//!
//! Rollback — reading *new* state with an *old* binary — is not testable from inside one
//! build, because the old binary is not here. The runbook documents what is safe to roll
//! back and what is not; this suite covers the forward direction only.

use std::path::PathBuf;

use rustcdc::checkpoint::{Checkpoint, FileCheckpoint};

fn fixture_path(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/state")
        .join(name)
}

/// Copy a frozen fixture into a temp state directory, with the permissions the server
/// writes.
///
/// `FileCheckpoint` refuses to read a checkpoint that is group- or world-readable — it
/// carries slot names and stream positions — and git stores no mode beyond the executable
/// bit, so a fixture checked into the repo arrives 0644. Restoring 0600 here is what makes
/// the fixture represent a real state directory rather than a repo file.
fn stage(name: &str, dir: &std::path::Path) -> PathBuf {
    let target = dir.join(name);
    std::fs::copy(fixture_path(name), &target).expect("stage the frozen fixture");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(&target, std::fs::Permissions::from_mode(0o600))
            .expect("restore the 0600 mode the server writes");
    }
    target
}

/// A checkpoint file written by a previous build must still load, position intact.
///
/// This is the one that matters most. `checkpoint_postgres.json` was produced by a real
/// `FileCheckpoint::save` and committed verbatim, `content_checksum` and all. A build that
/// cannot read it cannot resume any existing pipeline.
///
/// The assertions are on the *values*, not merely on "it parsed": a load that succeeds and
/// returns the wrong LSN is worse than one that fails, because it resumes from somewhere
/// nobody chose.
#[tokio::test]
async fn a_checkpoint_from_a_previous_build_still_loads() {
    use rustcdc::checkpoint::PostgresOffset;

    let dir = tempfile::tempdir().expect("tempdir");
    stage("checkpoint_postgres.json", dir.path());

    let checkpoint = FileCheckpoint::new(dir.path());

    let count = checkpoint
        .get_committed_count()
        .await
        .expect("the committed count must be readable");
    assert_eq!(
        count, 4242,
        "the committed-event count must survive the upgrade — it is what the rewind guard \
         compares against"
    );

    let offset = checkpoint
        .load()
        .await
        .expect("the frozen checkpoint must load")
        .expect("it is not empty");
    assert_eq!(offset.source_type(), "postgres");

    let decoded =
        PostgresOffset::from_bytes(&offset.encode().expect("re-encode")).expect("decode postgres");
    assert_eq!(
        decoded.lsn, 0x16B_6A70,
        "the stream position must survive byte-for-byte; resuming from a different LSN is \
         either replay or silent data loss"
    );
    assert_eq!(decoded.slot_name, "cdc_slot");
}

/// A tampered checkpoint must be refused, not silently accepted.
///
/// The `content_checksum` is the only thing standing between a corrupted or hand-edited
/// state file and a pipeline resuming from a position nobody wrote. This asserts the guard
/// is live in *this* build — a checksum that stopped being verified would look identical
/// to one that passes.
#[tokio::test]
async fn a_tampered_checkpoint_is_refused() {
    let dir = tempfile::tempdir().expect("tempdir");
    let body = std::fs::read_to_string(fixture_path("checkpoint_postgres.json"))
        .expect("read the frozen checkpoint");

    // Move the position forward without touching the checksum — the shape a careless
    // "just edit the LSN" recovery attempt takes.
    let tampered = body.replace("23816816", "23816999");
    assert_ne!(tampered, body, "the fixture must contain the LSN we edit");
    let path = dir.path().join("checkpoint_postgres.json");
    std::fs::write(&path, tampered).expect("write");
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt as _;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))
            .expect("0600, so the refusal is about the checksum and not the mode");
    }

    let checkpoint = FileCheckpoint::new(dir.path());
    let result = checkpoint.load().await;
    assert!(
        result.is_err(),
        "a checkpoint whose body does not match its checksum must be refused; accepting it \
         resumes the pipeline from a position no writer ever committed"
    );
}

/// Snapshot state written before `stopped` and `generation` existed must still load.
///
/// This is the exact hazard 0.11 → 0.12 presented. Both fields carry `#[serde(default)]`
/// upstream, so an old checkpoint loads — but that is a decision made in a crate this
/// project does not own, and a future release dropping the attribute would make every
/// in-flight backfill's state unreadable on upgrade.
///
/// The defaults are asserted, not just the parse. `stopped` defaulting to `true` would
/// silently abandon a running backfill; `generation` defaulting to something that collides
/// with a live one would make a re-snapshot look like a replay and get it dropped by the
/// idempotency guard.
#[test]
fn pre_0_12_snapshot_state_loads_with_safe_defaults() {
    // Exactly what 0.11 wrote: no `stopped`, no `generation`, no per-table `condition`.
    let legacy = serde_json::json!({
        "snapshot_id": "snap-legacy",
        "paused": false,
        "tables": [{
            "table": "public.orders",
            "pk_cursor": [4242],
            "is_complete": false,
            "chunks_emitted": 7,
            "rows_emitted": 35000
        }]
    });

    let state: rustcdc::IncrementalSnapshotState =
        serde_json::from_value(legacy).expect("a pre-0.12 snapshot state must still deserialize");

    assert_eq!(state.snapshot_id, "snap-legacy");
    assert!(
        !state.stopped,
        "state written before `stopped` existed must load as running — defaulting to \
         stopped would silently abandon an in-flight backfill on upgrade"
    );
    assert_eq!(
        state.generation, 0,
        "a checkpoint with no generation must start at the base generation, so previously \
         emitted rows keep the offsets they were written with"
    );

    let table = state.tables.first().expect("the table entry must survive");
    assert_eq!(table.rows_emitted, 35000, "progress must not be reset");
    assert_eq!(
        table.chunks_emitted, 7,
        "the chunk index must continue rather than restart, or `chunk_index` on emitted \
         events repeats values already used"
    );
    assert!(
        table.condition.is_none(),
        "a table with no recorded filter must load as unfiltered"
    );
}

/// Our own Kafka state-topic record must parse at every version we have written.
///
/// `record_version` is the field that makes this checkable at all. v1 is what shipped
/// before the schema-history split; v2 is current. A reader that cannot parse v1 turns a
/// `kafka_topic` upgrade into "the compacted topic is unreadable", which is unrecoverable
/// without republishing state by hand.
#[test]
fn every_kafka_state_record_version_still_parses() {
    #[derive(serde::Deserialize)]
    #[allow(dead_code)]
    struct Record {
        record_version: u8,
        source_type: String,
        offset_hex: String,
        committed_event_count: u64,
        saved_at_unix_ms: u64,
    }

    for (version, body) in [
        (
            1u8,
            serde_json::json!({
                "record_version": 1,
                "source_type": "postgres",
                "offset_hex": "7b226c736e223a32333831363831367d",
                "committed_event_count": 4242,
                "saved_at_unix_ms": 1_786_000_000_000u64
            }),
        ),
        (
            2,
            serde_json::json!({
                "record_version": 2,
                "source_type": "postgres",
                "offset_hex": "7b226c736e223a32333831363831367d",
                "committed_event_count": 4242,
                "saved_at_unix_ms": 1_786_000_000_000u64
            }),
        ),
    ] {
        let parsed: Record = serde_json::from_value(body)
            .unwrap_or_else(|e| panic!("record_version {version} must still parse: {e}"));
        assert_eq!(parsed.record_version, version);
        assert_eq!(parsed.committed_event_count, 4242);
    }
}

/// The `local_fs` owner lease must survive a restart across builds.
///
/// A lease this build cannot parse reads as *absent* — which is the safe direction for
/// availability and the unsafe one for correctness: the directory looks free and a second
/// writer takes it. Freezing the shape means a field rename shows up here rather than as
/// two processes interleaving checkpoints.
#[test]
fn the_owner_lease_record_still_parses() {
    let frozen = serde_json::json!({
        "owner": "cdc-host-1:4711:0a1b2c3d",
        "renewed_at_ms": 1_786_000_000_000u64,
        "epoch": 3
    });

    #[derive(serde::Deserialize)]
    struct Lease {
        owner: String,
        renewed_at_ms: u64,
        epoch: u64,
    }

    let lease: Lease =
        serde_json::from_value(frozen).expect("a frozen owner lease must still parse");
    assert_eq!(lease.owner, "cdc-host-1:4711:0a1b2c3d");
    assert_eq!(lease.epoch, 3);
    assert_eq!(lease.renewed_at_ms, 1_786_000_000_000);

    // The owner id is parsed by `is_dead_local_owner` as `host:pid:nonce`. A format change
    // that broke that would silently disable same-host crash takeover, turning every
    // restart into a full lease-TTL stall.
    let parts: Vec<&str> = lease.owner.splitn(3, ':').collect();
    assert_eq!(parts.len(), 3, "the owner id must stay host:pid:nonce");
    assert!(
        parts[1].parse::<u32>().is_ok(),
        "the middle component must remain a parseable pid"
    );
}

/// The processed-signal ledger must be readable across builds.
///
/// It is a plain line-per-key file precisely so this is hard to break, but it is the thing
/// standing between a redelivered `execute_snapshot` and a full table re-scan, so the
/// format is worth pinning.
#[test]
fn the_signal_ledger_format_is_stable() {
    let frozen = "kafka:cdc.signals:0:41\nkafka:cdc.signals:0:42\n";

    let keys: Vec<&str> = frozen
        .lines()
        .map(str::trim)
        .filter(|line| !line.is_empty())
        .collect();

    assert_eq!(
        keys,
        vec!["kafka:cdc.signals:0:41", "kafka:cdc.signals:0:42"]
    );
    for key in keys {
        let parts: Vec<&str> = key.split(':').collect();
        assert_eq!(
            parts.len(),
            4,
            "a ledger key must stay kafka:<topic>:<partition>:<offset>; it is derived from \
             the Kafka coordinate rather than the payload because signal_id is optional \
             and regenerated per delivery"
        );
        assert!(parts[2].parse::<i32>().is_ok(), "partition must parse");
        assert!(parts[3].parse::<i64>().is_ok(), "offset must parse");
    }
}

/// A world-readable checkpoint must be refused.
///
/// The state file carries the replication slot name and the exact stream position. The
/// guard is cheap and easy to lose in a refactor, and losing it is invisible — everything
/// keeps working, just readable by every account on the host. Asserted here because this
/// suite is the one that stages files with deliberate modes.
#[tokio::test]
#[cfg(unix)]
async fn a_group_readable_checkpoint_is_refused() {
    use std::os::unix::fs::PermissionsExt as _;

    let dir = tempfile::tempdir().expect("tempdir");
    let path = stage("checkpoint_postgres.json", dir.path());
    std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o644)).expect("loosen");

    let checkpoint = FileCheckpoint::new(dir.path());
    let error = checkpoint
        .load()
        .await
        .expect_err("a group-readable checkpoint must be refused");
    assert!(
        error.to_string().contains("0600"),
        "the refusal must name the mode it wants, since the fix is a chmod: {error}"
    );
}
